image: node:latest
stages:
- build
- test
- lint

before_script:
- npm install

cache:
  paths:
  - node_modules

build:
  stage: build
  script:
  - npm run build

test:
  stage: test
  script:
  - npm test

lint:
  stage: lint
  script:
  - yarn lint