export { LeftDownwardRightTriangle } from './patterns/leftDownwardRightTriangle'
export { LeftUpwardRightTriangle } from './patterns/leftUpwardRightTriangle'
export { PyramidTriangle } from './patterns/pyramidTriangle'
export { RightDownwardRightTriangle } from './patterns/rightDownwardRightTriangle'
export { RightUpwardRightTriangle } from './patterns/rightUpwardRightTriangle'
export { SquareMatrix, IMatrixStrategy } from './squareMatrix'
